name: Automated Build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  automated-build:
    uses: jpetazzo/workflows/.github/workflows/automated-build.yaml@main
    secrets:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
    with:
      DOCKER_HUB_USERNAME: enixsas
      PLATFORMS: linux/386,linux/amd64,linux/arm64,linux/arm/v7
